// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByUwXQSCWqqacn-SMqQ7U_doWeadZ55xw',
    appId: '1:1069677901233:web:fa39a1f98f482bc7593990',
    messagingSenderId: '1069677901233',
    projectId: 'easy-pms',
    authDomain: 'easy-pms.firebaseapp.com',
    storageBucket: 'easy-pms.firebasestorage.app',
    measurementId: 'G-054LE8NGKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqST52hFGWUpIODo9otHKqv3Wc99HXDPo',
    appId: '1:1069677901233:android:a7e4844b645bdcf7593990',
    messagingSenderId: '1069677901233',
    projectId: 'easy-pms',
    storageBucket: 'easy-pms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOeGclMqxEqeUR0tNj-XJDMkOPLvLbLPA',
    appId: '1:1069677901233:ios:196e208d83d13250593990',
    messagingSenderId: '1069677901233',
    projectId: 'easy-pms',
    storageBucket: 'easy-pms.firebasestorage.app',
    iosBundleId: 'com.example.easyPms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOeGclMqxEqeUR0tNj-XJDMkOPLvLbLPA',
    appId: '1:1069677901233:ios:196e208d83d13250593990',
    messagingSenderId: '1069677901233',
    projectId: 'easy-pms',
    storageBucket: 'easy-pms.firebasestorage.app',
    iosBundleId: 'com.example.easyPms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByUwXQSCWqqacn-SMqQ7U_doWeadZ55xw',
    appId: '1:1069677901233:web:b383259012b6e00f593990',
    messagingSenderId: '1069677901233',
    projectId: 'easy-pms',
    authDomain: 'easy-pms.firebaseapp.com',
    storageBucket: 'easy-pms.firebasestorage.app',
    measurementId: 'G-LZHS7PG1PF',
  );
}
